export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_ERROR = 'LOAD_USER_ERROR';
export const LOAD_USER_TASKS_REQUEST = 'LOAD_USER_TASKS_REQUEST';
export const LOAD_USER_TASKS_SUCCESS = 'LOAD_USER_TASKS_SUCCESS';
export const LOAD_USER_TASKS_ERROR = 'LOAD_USER_TASKS_ERROR';