export const ON_LOGIN = 'ON_LOGIN';
export const ON_LOGIN_REQUEST = 'ON_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_SUCCESS_REQUEST = 'LOGIN_SUCCESS_REQUEST';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_FAILED_REQUEST = 'LOGIN_FAILED_REQUEST';
