export const ADD_TASK_FORM_REQUEST = 'ADD_TASK_FORM_REQUEST';
export const OPEN_TASK_FORM = 'OPEN_TASK_FORM';
export const CANCEL_TASK_FORM_REQUEST = 'CANCEL_TASK_FORM_REQUEST';
export const CANCELED_TASK_FORM = 'CANCELED_TASK_FORM';